apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gologserver
  name: gologserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gologserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gologserver
    spec:
      containers:
      - image: "jojii/gologserver:v1.1"
        name: gologserver
        volumeMounts:
        - name: config
          mountPath: /app/data/
        env:
        - name: GOLOG_LOG_LEVEL
          value: debug
          name: GOLOG_CONFIG
          value: /app/data/config.yaml
      volumes:
      - name: config
        configMap:
          name: logserverconfig
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gologserver
  name: gologserver
spec:
  ports:
  - name: 9001-80
    port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: gologserver
  type: NodePort
  externalIPs:
  - <IP>
status:
  loadBalancer: {}
